- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: clock
          hour-format: 12h
          timezones:
            - timezone: America/Chicago
              label: Saint Paul
            - timezone: America/Detroit
              label: Tampa

        - type: bookmarks
          groups:
            - color: 335 100 68
              links:
                - title: ProtonMail
                  url: https://mail.proton.me/u/1/inbox
                - title: Discord
                  url: https://discord.com/channels/@me
                - title: Slack
                  url: https://app.slack.com/client/T03FNQ916/C3ZEW1HMG
                - title: LinkedIn
                  url: https://www.linkedin.com/messaging
            - title: Life
              color: 275 100 68
              links:
                - title: YNAB
                  url: https://app.ynab.com/1f5927dd-12de-4d35-a163-8eff9b26b5ef/accounts
                - title: Notes
                  url: https://notes.com
            - title: Entertainment
              color: 6 100 68
              links:
                - title: YouTube
                  url: https://www.youtube.com/
                - title: Nebula
                  url: https://www.nebula.tv/featured
                - title: Patreon
                  url: https://www.patreon.com/home
            - title: Social
              color: 215 100 68
              links:
                - title: Bluesky
                  url: https://bsky.app
                - title: Reddit
                  url: https://www.reddit.com/

    - size: full
      widgets:
        - type: group
          widgets:
            - type: rss
              title: Local
              limit: 15
              collapse-after: 5
              cache: 12h
              feeds:
                - url: https://sahanjournal.com/feed/
                  title: Sahan Journal
                - url: https://unicornriot.ninja/feed/
                  title: UNICORN RIOT
            - type: rss
              title: The Craft
              limit: 15
              collapse-after: 5
              cache: 12h
              feeds:
                - url: https://blog.incrementalforgetting.tech/feed
                  title: Incremental Forgetting
                - url: https://www.saiyangrowthletter.com/feed
                  title: Saiyan Growth Letter
                - url: https://thecodist.com
                  title: The Codist
                - url: https://blog.pragmaticengineer.com/rss
                  title: The Pragmatic Engineer
                - url: https://blog.railway.tech/rss.xml
                  title: Railway Blog
            - type: rss
              title: Trivia
              limit: 15
              collapse-after: 5
              cache: 12h
              feeds:
                - url: https://acoup.blog/feed
                  title: ACOUP

        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UCJPHc5wprYeNF0K5ITwPBgA # Behind the Bastards (podcast)
            - UCJBl1V_PdBNJiUMa40eQdww # Respect the Dead (podcast)
            - UCsBjURrPoezykLs9EqgamOA # Fireship
            - UClt01z1wHHT7c5lKcU8pxRQ # hbomberguy
            - UC7-E5xhZBZdW-8d7V80mzfg # Jenny Nicholson
            - UCaTSjmqzOO-P8HmtVW3t7sA # Todd in the Shadows
            - UC_-ywsA9-7dSTbWmdQdltbQ # The Musings of a Crouton

        - type: group
          title: Reddit
          widgets:
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true
            - type: reddit
              subreddit: homelab
              show-thumbnails: true
            - type: reddit
              subreddit: news
              show-thumbnails: true
            - type: reddit
              subreddit: EnoughMuskSpam
              show-thumbnails: true
            - type: reddit
              subreddit: react
              show-thumbnails: true
            - type: reddit
              subreddit: htmx
              show-thumbnails: true
            - type: reddit
              subreddit: golang
              show-thumbnails: true
            - type: reddit
              subreddit: reactnative
              show-thumbnails: true
            - type: reddit
              subreddit: galaxyzflip
              show-thumbnails: true
            - type: reddit
              subreddit: android
              show-thumbnails: true

    - size: small
      widgets:
        - type: weather
          location: Saint Paul, Minnesota, United States
          units: imperial # alternatively "metric"
          hour-format: 12h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

        - type: calendar
          first-day-of-week: monday

        - type: releases
          cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - glanceapp/glance
            - facebook/react
            - facebook/react-native
            - TanStack/router

        - type: markets
          title: Retweet to die faster
          markets:
            - symbol: DX=F
              name: US Dollar
            - symbol: ^IXIC
              name: NASDAQ
            - symbol: SPY
              name: S&P 500
            - symbol: TSLA
              name: Tesla
            - symbol: NVDA
              name: NVIDIA
            - symbol: AAPL
              name: Apple
            - symbol: MSFT
              name: Microsoft
            - symbol: BTC-USD
              name: Bitcoin
