- name: Tech
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: to-do

        - type: clock
          hour-format: 12h

        - type: weather
          location: Saint Paul, Minnesota, United States
          units: imperial # alternatively "metric"
          hour-format: 12h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

        - type: calendar
          first-day-of-week: sunday

        - type: markets
          title: Retweet to make it die faster
          markets:
            - symbol: NVDA
              name: NVIDIA
            - symbol: AMD
              name: AMD
            - symbol: CRWV
              name: CoreWeave
            - symbol: SNOW
              name: Snowflake
            - symbol: PLTR
              name: Palantir
            - symbol: ORCL
              name: Oracle
            - symbol: GOOGL
              name: Google
            - symbol: AAPL
              name: Apple
            - symbol: AMZN
              name: Amazon
            - symbol: TSLA
              name: Tesla
            - symbol: META
              name: FaceBook
            - symbol: MSFT
              name: Microsoft
            - symbol: BTC-USD
              name: Bitcoin

    - size: full
      widgets:
        - type: group
          widgets:
            - type: rss
              title: Pluralistic
              style: detailed-list
              limit: 15
              collapse-after: 5
              cache: 12h
              feeds:
                - url: https://pluralistic.net/feed
                  title: Pluralistic
            - type: rss
              title: Futurism
              style: detailed-list
              limit: 15
              collapse-after: 5
              cache: 12h
              feeds:
                - url: https://futurism.com/feed
                  title: Futurism
            - type: rss
              title: Better Offline
              style: detailed-list
              limit: 15
              collapse-after: 5
              cache: 12h
              feeds:
                - url: https://www.wheresyoured.at/rss
                  title: Ed Zitron's Where's Your Ed At
            - type: rss
              title: React Native
              style: detailed-list
              limit: 15
              collapse-after: 5
              cache: 12h
              feeds:
                - url: https://reactnative.dev/blog/rss.xml
                  title: React Native
            - type: rss
              title: React Native
              style: detailed-list
              limit: 15
              collapse-after: 5
              cache: 12h
              feeds:
                - url: https://reactnative.dev/blog/rss.xml
                  title: React Native
            - type: hacker-news
              collapse-after: 10
            - type: lobsters
              collapse-after: 10
            - type: rss
              title: Other
              limit:
              collapse-after: 10
              cache: 12h
              feeds:
                - url: https://blog.incrementalforgetting.tech/feed
                  title: Incremental Forgetting
                - url: https://www.normaltech.ai/feed
                  title: AI Snake Oil
                - url: https://thecodist.com/rss
                  title: The Codist
                - url: https://blog.pragmaticengineer.com/rss
                  title: The Pragmatic Engineer
                - url: https://tidyfirst.substack.com/feed?sectionId=79696
                  title: "Software Design: Tidy First?"
                - url: https://blog.railway.com/rss.xml
                  title: Railway Blog
                - url: https://feeds.captivate.fm/techpolicypress
                  title: Tech Policy.press
                - url: https://react.dev/rss.xml
                  title: React Blog

        # - icon: https://yt3.googleusercontent.com/pJTCOISMYIi2iHJpSccILsQr7XjVonBiS_MDzSw9TO_L4QVhtc0L5S78mFGziHDdior_QKxyfQ=s160-c-k-c0x00ffffff-no-rj
        # - type: html
        #   source: |
        #     <img alt="My YouTube profile pic, in whom I am well pleased" class="ytCoreImageHost yt-spec-avatar-shape__image ytCoreImageFillParentHeight ytCoreImageFillParentWidth ytCoreImageContentModeScaleToFill ytCoreImageLoaded" src="https://yt3.googleusercontent.com/pJTCOISMYIi2iHJpSccILsQr7XjVonBiS_MDzSw9TO_L4QVhtc0L5S78mFGziHDdior_QKxyfQ=s160-c-k-c0x00ffffff-no-rj">

        - type: videos
          style: grid-cards
          collapse-after-rows: 3
          channels:
            - UCsBjURrPoezykLs9EqgamOA # Fireship
            - UCsdzuPs5NKvdsBkQnP7Af8w # Better Offline
            - UChIs72whgZI9w6d6FhwGGHA # Gamers Nexus
            - UC-kM5kL9CgjN9s9pim089gg # Adam Conover
            - UC6Om9kAkl32dWlDSNlDS9Iw # DEFCON Conference
            - UCKgDsBDpYdZf2mbRzcEC8FA # Software Mansion
            - UCFQMnBA3CS502aghlcr0_aw # Coffeezilla
            - UC28n0tlcNSa1iPe5mettocg # voidzilla
            - UCyU5wkjgQYGRB0hIHMwm2Sg # Syntax
            - UCl2mFZoRqjw_ELax4Yisf6w # Louis Rossman
            - UCshObcm-nLhbu8MY50EZ5Ng # Benn Jordan
            - UCs_tLP3AiwYKwdUHpltJPuA # GOTO Conferences

        - type: group
          widgets:
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true
            - type: reddit
              subreddit: neovim
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true
            - type: reddit
              subreddit: antiai
              show-thumbnails: true

    - size: small
      title: Watch
      widgets:
        - type: change-detection
          instance-url: https://lemonade.changedetection.io/detachable-yay
          token: ${CHANGE_DETECTION_TOKEN}

        - type: releases
          cache: 1d
          limit: 25
          collapse-after: 5
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - facebook/react-native
            - facebook/react
            - bigskysoftware/htmx
            - LazyVim/LazyVim
            - TanStack/router
            - glanceapp/glance
            - go-gitea/gitea
            - immich-app/immich
            - syncthing/syncthing

        - type: monitor
          cache: 1m
          limit: 25
          collapse-after: 5
          title: Services
          sites:
            - title: Blog/Portfolio
              url: https://kimfreechack.me
              icon: /assets/logo-minimal-v1.png
            - title: Railway
              url: https://railway.com
              icon: /assets/railway-logo.png
            - title: Codeberg
              url: https://codeberg.org
              icon: /assets/github-logo.png
            - title: GitHub
              url: https://github.com
              icon: /assets/codeberg-logo.png
